---

site_name: PowervRO
repo_url: https://github.com/jakkulabs/PowervRO
site_author: JakkuLabs
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "PowervRO is licensed under the <a href='https://github.com/jakkulabs/PowervRO/raw/master/LICENSE'>MIT license"
pages:
- 'Home' : 'index.md'
- 'Change log' : 'CHANGELOG.md'
- 'Functions': 
    - Add-vROActionPermission : functions/Add-vROActionPermission.md
    - Add-vROCategoryPermission : functions/Add-vROCategoryPermission.md
    - Add-vROConfigurationElementPermission : functions/Add-vROConfigurationElementPermission.md
    - Add-vROPackagePermission : functions/Add-vROPackagePermission.md
    - Add-vROResourceElementPermission : functions/Add-vROResourceElementPermission.md
    - Add-vROWorkflowPermission : functions/Add-vROWorkflowPermission.md
    - Connect-vROServer : functions/Connect-vROServer.md
    - Disconnect-vROServer : functions/Disconnect-vROServer.md
    - Export-vROAction : functions/Export-vROAction.md
    - Export-vROConfigurationElement : functions/Export-vROConfigurationElement.md
    - Export-vROPackage : functions/Export-vROPackage.md
    - Export-vROPlugin : functions/Export-vROPlugin.md
    - Export-vROResourceElement : functions/Export-vROResourceElement.md
    - Export-vROWorkflow : functions/Export-vROWorkflow.md
    - Export-vROWorkflowIcon : functions/Export-vROWorkflowIcon.md
    - Export-vROWorkflowSchema : functions/Export-vROWorkflowSchema.md
    - Get-vROAction : functions/Get-vROAction.md
    - Get-vROActionPermission : functions/Get-vROActionPermission.md
    - Get-vROAPIEndpoint : functions/Get-vROAPIEndpoint.md
    - Get-vROCategory : functions/Get-vROCategory.md
    - Get-vROCategoryPermission : functions/Get-vROCategoryPermission.md
    - Get-vROConfigurationElement : functions/Get-vROConfigurationElement.md
    - Get-vROConfigurationElementPermission : functions/Get-vROConfigurationElementPermission.md
    - Get-vROPackage : functions/Get-vROPackage.md
    - Get-vROPackagePermission : functions/Get-vROPackagePermission.md
    - Get-vROPlugin : functions/Get-vROPlugin.md
    - Get-vROResourceElement : functions/Get-vROResourceElement.md
    - Get-vROResourceElementPermission : functions/Get-vROResourceElementPermission.md
    - Get-vROUser : functions/Get-vROUser.md
    - Get-vROVersion : functions/Get-vROVersion.md
    - Get-vROWorkflow : functions/Get-vROWorkflow.md
    - Get-vROWorkflowExecution : functions/Get-vROWorkflowExecution.md
    - Get-vROWorkflowExecutionResult : functions/Get-vROWorkflowExecutionResult.md
    - Get-vROWorkflowExecutionState : functions/Get-vROWorkflowExecutionState.md
    - Get-vROWorkflowPermission : functions/Get-vROWorkflowPermission.md
    - Import-vROAction : functions/Import-vROAction.md
    - Import-vROConfigurationElement : functions/Import-vROConfigurationElement.md
    - Import-vROPackage : functions/Import-vROPackage.md
    - Import-vROPlugin : functions/Import-vROPlugin.md
    - Import-vROResourceElement : functions/Import-vROResourceElement.md
    - Import-vROWorkflow : functions/Import-vROWorkflow.md
    - Invoke-vROAction : functions/Invoke-vROAction.md
    - Invoke-vRORestMethod : functions/Invoke-vRORestMethod.md
    - Invoke-vROWorkflow : functions/Invoke-vROWorkflow.md
    - New-vROCategory : functions/New-vROCategory.md
    - New-vROParameterDefinition : functions/New-vROParameterDefinition.md
    - Remove-vROAction : functions/Remove-vROAction.md
    - Remove-vROActionPermission : functions/Remove-vROActionPermission.md
    - Remove-vROCategory : functions/Remove-vROCategory.md
    - Remove-vROCategoryPermission : functions/Remove-vROCategoryPermission.md
    - Remove-vROConfigurationElement : functions/Remove-vROConfigurationElement.md
    - Remove-vROConfigurationElementPermission : functions/Remove-vROConfigurationElementPermission.md
    - Remove-vROPackage : functions/Remove-vROPackage.md
    - Remove-vROPackagePermission : functions/Remove-vROPackagePermission.md
    - Remove-vROResourceElement : functions/Remove-vROResourceElement.md
    - Remove-vROResourceElementPermission : functions/Remove-vROResourceElementPermission.md
    - Remove-vROWorkflow : functions/Remove-vROWorkflow.md
    - Remove-vROWorkflowPermission : functions/Remove-vROWorkflowPermission.md
    - Set-vROPluginState : functions/Set-vROPluginState.md
